GET http://localhost:3000/content
content-type: application/json

{
    //"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphaG9yIiwicGFzc3dvcmQiOiIxMjM0NTY3OCIsImlhdCI6MTYzNTY5MjIyNCwiZXhwIjoxNjM1Njk1ODI0fQ.cJjHdLo9Z0PK5O2pPh9sYfgomZuBtpZProJUXH7yrqw"
}

###
POST http://localhost:3000/login
content-type: application/json

{
    "username": "jahor",
    "password": "12345678"
}

###
POST http://localhost:3000/register
content-type: application/json

{
    "username": "biba",
    "password": "12345678"
}